apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-pipeline
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # after kargo is installed (wave -1) and apps (wave 0)
spec:
  project: default
  source:
    repoURL: https://github.com/amaljithh/kuztomise-argo-poc.git
    targetRevision: HEAD
    path: kargo-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
