apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amaljithh/kuztomise-argo-poc.git
    targetRevision: HEAD
    path: overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
